version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/chromium/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    assignees:
      - "zoracon"
    commit-message:
      prefix: "npmauto"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "zoracon"
    versioning-strategy: widen
