env:
  browser: true
  es6: true
  jquery: true
  webextensions: true
extends: 'eslint:recommended'
globals:
  # false to disallow overwriting
  require: false
  _: false
parserOptions:
  # strict mode
  sourceType: module
rules:
  curly:
    - error
    - multi-line
  dot-notation: warn
  indent:
    - error
    - 2
    - outerIIFEBody: 0
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  new-cap: error
  no-array-constructor: error
  no-bitwise: warn
  no-caller: error
  no-console: off
  no-eval: warn
  no-implied-eval: warn
  no-iterator: error
  no-loop-func: error
  no-multi-str: warn
  no-new: error
  no-new-func: warn
  no-new-object: error
  no-new-wrappers: error
  no-proto: error
  no-script-url: warn
  no-shadow: warn
  no-shadow-restricted-names: error
  no-trailing-spaces: error
  no-unused-expressions: warn
  brace-style:
    - error
    - 1tbs
  semi: error
