name: 'Alexa Labeller'
description: 'Label PRs with Top Alexa Labels'
inputs:
  github-token:
    description: 'Token for the repository'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
