name: 'Alexa Labeller'
description: 'Label PRs with Top Alexa Labels'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
    required: true
runs:
  using: 'node10'
  main: 'dist/index.js'
