#!/bin/sh
#
#   hooks/precommit hook script of https-everywhere.
#
#   Author: Jonathan Davies <jpdavs@gmail.com>
#

echo "$(date -R): Stashing unrelated changes in Git..."
git stash -q --keep-index

trap 'echo "$(date -R): Reverting Git stash..."; git stash pop -q' EXIT

# Only run tests if our rulesets have been changed.
RULESET_PATTERN="src/chrome/content/rules/"
CHANGED_RULESETS="$(git diff --cached --name-only | grep $RULESET_PATTERN)"

if [ "$CHANGED_RULESETS" ]; then
    echo "$(date -R): Running ruleset validation tests on changed rulesets:"

    for FILE in $CHANGED_RULESETS; do
        if [ ! -f $FILE ]; then
            echo "$(date -R): Skipped validation of $FILE - not found."
            continue
        fi

        ./utils/trivial-validate.py $FILE > /dev/null
        RESULT=$?

        if [ $RESULT -eq 1 ]; then
            echo "$(date -R): Failure encountered during ruleset validation."
            exit $RESULT
        fi
    done

    echo "$(date -R): Ruleset validation successful."
else
    echo "$(date -R): Skipped ruleset validation tests, no changes in" \
        "$RULESET_PATTERN."
fi

exit 0
