#!/bin/sh
#
#   hooks/precommit hook script of https-everywhere.
#
#   Author: Jonathan Davies <jpdavs@gmail.com>
#

echo "$(date -R): Stashing unrelated changes in Git..."
git stash -q --keep-index

# Only run tests if our rulesets have been changed.
RULESET_PATTERN="src/chrome/content/rules/"
CHANGED_RULESETS="$(git diff --cached --name-only | grep $RULESET_PATTERN)"

if [ "$CHANGED_RULESETS" ]; then
    echo "$(date -R): Running ruleset validation tests on changed rulesets:"
    ./utils/trivial-validate.py $(git diff --cached --name-only) > /dev/null
    RESULT=$?

    if [ $RESULT -eq 1 ]; then
        echo "$(date -R): Failure encountered during ruleset validation."
    else
        echo "$(date -R): Ruleset validation successful."
    fi
else
    echo -n "$(date -R): Skipped ruleset validation tests, no changes in "
    echo "$RULESET_PATTERN."
fi

echo "$(date -R): Reverting Git stash..."
git stash pop -q

exit $RESULT
