#!/bin/sh

# create $1.xml, mapping $1 and www.$1 to https://www.$1

if [ -z "$1" ]
then
  echo "syntax: $0 example.com" >&2
  exit 1
fi

dest="$1".xml
if [ -f "$dest" ]
then
  echo "error: $dest already exists." >&2
  exit 1
fi

if echo "$1" | grep -i '^www' >/dev/null
then
  echo "error: omit leading www" >&2
  exit 1
fi

if echo "$1" | grep -v '\.' >/dev/null
then
  echo "error: domain should probably contain a dot" >&2
  exit 1
fi

escaped=$(echo "$1" | sed 's/\./\\./g' )

cat > "$dest" <<END
<ruleset name="$1">
  <rule from="^http://(www\.)?$escaped/" to="https://www.$1/"/>
</ruleset>
END

echo "$0: created $dest; please examine it." >&2
