#!/bin/sh
# THIS IS NOT A RULE, but a shell script that looks for common problems
# and typos in rules.

echo "-- Rules not anchored to beginning of a line:"
grep from= *.xml | cut -d\" -f2 | grep '^[^^]' || echo "(None.)"
echo
echo "-- Rules with unescaped dots:"
grep from= *.xml | cut -d\" -f2 | grep '[^\]\.[^*]' || echo "(None.)"
echo
echo "-- Rules not containing trailing slash in from pattern:"
grep from= *.xml | cut -d\" -f2 | grep -v '//.*/' || echo "(None.)"
echo
echo "-- Rules not containing trailing slash in to pattern:"
grep 'to="' *xml | sed 's/^.*to="//' | sed 's/\".*$//' | grep -v '//.*/' || echo "(None.)"
echo
echo "-- Rules with missing closing slash in rule XML tag:"
grep to= *xml | grep '[^/]>' || echo "(None.)"
echo
echo "-- Rules redirecting to http in to pattern:"
grep 'to="' *xml | sed 's/^.*to="//' | sed 's/\".*$//' | grep '^http:' || echo "(None.)"
echo
if [ $(which xmllint) ]
then
  echo "-- Rules with syntatically invalid XML:"
  none=true
    for rule in *.xml
    do
      xmllint "$rule" >/dev/null 2>&1 || { echo $rule; none=false; }
    done
  $none && echo "(None.)"
else
  echo "-- Could not check XML validity because xmllint not found."
fi
